apiVersion: v1
kind: Service
metadata:
  name: monitoramento
spec:
  selector:
    app: monitoramento
  ports:
    - protocol: TCP
      port: 3000  # A porta que o serviço expõe
      targetPort: 3000  # Porta interna no contêiner
  type: NodePort
