apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoramento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoramento
  template:
    metadata:
      labels:
        app: monitoramento
    spec:
      containers:
        - name: monitoramento
          image: anttonys/monitor:latest   # Altere se precisar de uma tag diferente
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000   # A porta em que o serviço estará ouvindo
      # Caso a imagem seja privada, adicione a configuração de pull secret
      imagePullSecrets:
        - name: my-registry-secret1
---
apiVersion: v1
kind: Service
metadata:
  name: monitoramento
spec:
  selector:
    app: monitoramento
  ports:
    - protocol: TCP
      port: 3000      # A porta exposta no serviço
      targetPort: 3000 # Porta interna no container
  type: NodePort       # Expondo o serviço para o Minikube
