apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort                   # Permite acesso externo (pelo IP do Minikube)
  selector:
    app: nginx                      # O mesmo label usado no deployment para associar os pods
  ports:
    - port: 80                      # Porta exposta
      targetPort: 80                 # Porta interna do container
      nodePort: 30080                # Porta no nรณ do Minikube (http://<minikube-ip>:30080)
